spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kasir
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: admin
      password: admin

server:
  port: 8080 